### ISSUE TITLE
PlayFabSDKExample build fails on OS X

### ISSUE THREAD

**Issue by aardvarkk** [PlayFab/Cocos2d-xSDK#31]
To reproduce, run `cocos run -p mac`. The following error is produced:

```
Cocos2d-xSDK/PlayFabSDKExample/Classes/playfab/PlayFabClientDataModels.h:4:10: fatal error: 'playfab/PlayFabBaseModel.h' file not found
```

**Comment by aardvarkk** [comment]
Looks like an issue with include directories not being set correctly. I will try to fix it.

**Comment by aardvarkk** [comment]
After fixing include directories and adding files to the project I'm stuck with hundreds of errors related to attempts to cast function pointers to void* using static_cast<>. For instance, this line:

`httpRequest->SetResultCallback(static_cast<void*>(callback));`

throws the error an error about not being allowed to cast from a callback type void pointer (including arguments) to a normal void pointer (without arguments).

**Comment by pgilmorepf** [comment]
We hope to make improvements to the Cocos sdk soon, and some or all of your concerns will likely be addressed.

**Comment by MarcoWilliamsPF** [comment]
@aardvarkk  is this still happening for you?  We have released a few updates since your post Jan 8th,  can you confirm?

**Comment by aardvarkk** [comment]
Unfortunately I'm no longer working with PlayFab so I can't test this out again, sorry.

**Comment by bvanous** [comment]
Sorry to hear that. What were the key elements that led you to dropping
PlayFab usage?

Brendan

**Comment by aardvarkk** [comment]
Part of it was that I didn't really understand the interaction between PlayFabSDK and Photon. It seemed like a muddy offering and I wasn't sure how the pieces fit together. Part of it was the lack of proper SDK support for the engine I was working with (Cocos). And part of it was that we needed full server control and it looked like if we got something working on PlayFab it'd be using Photon and then we'd be both in a Windows environment and potentially unable to run whatever code we wanted on the server side.

**Comment by bvanous** [comment]
Sorry, do you mean you had trouble with Photon's SDK (
https://www.photonengine.com/en/Turnbased/Download) or ours (
https://api.playfab.com/sdks/cocos2d-x)? We do have a tutorial on getting
started using Photon in conjunction with PlayFab here (). Did you get a
chance to review that before you started?

But yes, it is the case that with Photon, you are using a shared server for
making your Rooms for players. If you're looking for more direct control of
the server logic, you would want to look into building a custom game server
- potentially using Photon Server - which we could then host for you in our
scalable EC2 offering. Those EC2 servers are all Windows 2K12 R2, so it
would be Windows for both, at that point.

Brendan

**Comment by aardvarkk** [comment]
I honestly didn't even really get to the point of using the Photon SDKs.
They were confusing enough (why are there three?!). It looked like
"Realtime" was the best match for what we were doing. But then we needed to
implement a custom Photon server, too, and that felt a bit scary -- not
having the direct server control, especially during initial development.
Perhaps we'll try it again once the product is developed and working and it
needs to scale better, but it just didn't feel simple enough.

With PlayFab, the fact that the Cocos SDK didn't appear to be getting much
attention and the fact that the examples didn't build caused me to move on.
We were pretty locked in to Cocos and if the integration wasn't tight and
working nicely then I didn't want to spend a ton of time trying to figure
it all out.

**Comment by bvanous** [comment]
Interesting - it sounds like you may have some feedback for the Exit Games
team (the folks who make the Photon tech) as well, then.

For our SDKs, we have made a few updates to the Cocos2d-x SDK since the
start of the year. At the moment, we are aware that it lacks support for
Android, but we have an update in progress which will address that. Are
there other areas you saw that needed work? In general, the samples are
designed to show as simply as possible how the Web API calls work, since
they're at the base level of everything, and we make sure to provide some
examples of usage in each SDK as a "template" of sorts for implementation.
We will be providing more detailed samples across all SDKs as soon as we
can.

Brendan

**Comment by aardvarkk** [comment]
I think my primary feedback would be just that the examples should compile
with no real effort. Cocos is cross-platform, and this particular issue was
opened because at the time that I got the examples they would not compile
under the latest version of XCode (even after I fixed up some project
settings that weren't properly including necessary headers). Beyond that I
don't have much of a recommendation for the examples other than that they
should get straight to the point. I had a some trouble figuring out how
PlayFab and Photon were supposed to fit together, and it was a bit bizarre
when I was starting Photon accounts from within my PlayFab account --
couldn't this be done opaquely to your end users so that they don't even
have to know they're working with Photon behind the scenes?

Anyway, I think the service you guys are trying to offer would be valuable
and makes a lot of sense -- the focus just has to be put squarely on
communicating what problems your product is trying to solve and have your
examples demonstrate that in the simplest manner possible.

**Comment by bvanous** [comment]
Thanks, greatly appreciate you taking the time to get us this feedback.
Very much understood on the SDK and samples - we'll be working on exactly
that over the next little while. For Photon though, we can't really take
care of the authentication and Room/Lobby use from the service side, so we
would need to create a client wrapper which manages that. Which isn't a
non-starter, it's just not something we'll be working on in the near
future. If we get feedback from others along the same lines though, that
would be the thing that drives it up our priority list.

Brendan

**Comment by pgilmorepf** [comment]
For tracking, we just released an update to Cocos which should greatly improve the Cocos process.  Android, iOS, and Win32 should compile, run, and test successfully with minimal effort.  I'm sorry to hear that this update came too late for you.  Perhaps someday you'll take another look.  Cheers!
https://github.com/PlayFab/Cocos2d-xSDK/pull/43
