### ISSUE TITLE
C++/Cocos2d-x SDK not passing Undefined Behaviour Sanitizer due to weird nullptr casting to access static member

### ISSUE THREAD

**Issue by ForestRingGames** [PlayFab/Cocos2d-xSDK#64]
The Cocos2d-x C++ and Cocos2d-x SDKs very frequently do something like this:

`(static_cast<PlayFabClientAPI*>(userData))->mUserSessionTicket = outResult.SessionTicket;`

Basically userData is often a `nullptr` which causes UBSAN to be very confused. `mUserSessionTicket` is a static member of `PlayFabClientAPI`.

It would be better/cleaner to just actually do that without the cast. This clearly shows the intention.
`PlayFabClientAPI::mUserSessionTicket = outResult.SessionTicket;`

**Comment by pgilmorepf** [comment]
AHA, yes... Good catch. This was a missed element of a recent refactor.
Thanks for reporting this.
I'll try to fix it soon.

**Comment by pgilmorepf** [comment]
Oh... sorry for the delay on this.  Apparently I stealth-fixed it on myself by accident, quite a while ago.
I've verified the code, and clientSessionTicket in PlayFab settings is set correctly, without using this incorrect cast.  Thanks for the report, and sorry again for the delay.
